name: mddatasetexplorer_env
dependencies:
  - python=3.11
  - pip
  - python-dotenv # For environment variables
  - jupyterlab>=4
  # Reduction methods
  - umap-learn
  - hdbscan
  - scikit-learn
  # Visualization
  - matplotlib
  # Embeddings tools
  - nltk
  - scikit-learn
  - pytorch
  - transformers
  - langchain
  - tiktoken
  - chromadb # Vector storage
  # Logging
  - loguru
  # IU : Web app
  - streamlit
  # Graph
  - networkx
  - pyvis
  - pip:
      # watermark: keep track of dependency versions
      - watermark
      - datamapplot
      - langchain_core
      - langchain_openai
      - sentence_transformers
      - concurrent


