name: mddatasetexplorer-env
dependencies:
  - python=3.11
  - pip
  - python-dotenv # For environment variables
  - jupyterlab>=4
  - concurrent
  # Embeddings tools
  - nltk
  - scikit-learn
  - pytorch
  - sentence_transformers
  - transformers
  - chromadb # Vector storage
  # Logging
  - loguru
  # IU : Web app
  - streamlit
  # Graph
  - networkx
  - pip:
      # watermark: keep track of dependency versions
      - watermark