name: mddatasetexplorer-env
dependencies:
  - python=3.11
  - pip
  - python-dotenv # For environment variables
  - jupyterlab>=4
  - concurrent
  # Reduction methods
  - umap-learn
  - hdbscan
  - scikit-learn
  # Visualization
  - matplotlib
  # Embeddings tools
  - nltk
  - scikit-learn
  - pytorch
  - sentence_transformers
  - transformers
  - langchain_core
  - langchain
  - langchain_openai
  - tiktoken
  - chromadb # Vector storage
  # Logging
  - loguru
  # IU : Web app
  - streamlit
  # Graph
  - networkx
  - pyvis
  - pip:
      # watermark: keep track of dependency versions
      - watermark
      - datamapplot